
data = {
    0 : {
        'PATH' :'../pic/other/peabullet.png',
        'IMAGE_INDEX_MAX' : 0,
        'IMAGE_INDEX_CD' : 0,
        'POSITION_CD' : 0.008,
        'SUMMON_CD': 1e8,
        'SIZE' : (44,44),
        'SPEED' : (4,0),
        'CAN_LOOT' : False,
        'PRICE' : 0,
    },
    1 : {
        'PATH' :'../pic/zombie/0/%d.png',
        'IMAGE_INDEX_MAX': 15,
        'IMAGE_INDEX_CD': 0.2,
        'POSITION_CD': 0.2,
        'SUMMON_CD': 1e8,
        'SIZE': (100,128),
        'SPEED': (-2.5, 0),
        'CAN_LOOT': False,
        'PRICE': 0,
    },
    2: {
        'PATH': '../pic/other/sunlight/%d.png',
        'IMAGE_INDEX_MAX': 30,
        'IMAGE_INDEX_CD': 0.06,
        'POSITION_CD': 0.06,
        'SUMMON_CD': 1e8,
        'SIZE': (80,80),
        'SPEED': (0,2),
        'CAN_LOOT': True,
        'PRICE': 5,
    },
    3: {
        'PATH': '../pic/plant/sunflower/%d.png',
        'IMAGE_INDEX_MAX': 19,
        'IMAGE_INDEX_CD': 0.07,
        'POSITION_CD': 1e9,
        'SUMMON_CD': 8,
        'SIZE': (128, 128),
        'SPEED': (0, 0),
        'CAN_LOOT': False,
        'PRICE': 30,
    },
    4: {
        'PATH': '../pic/plant/peashooter/%d.png',
        'IMAGE_INDEX_MAX': 15,
        'IMAGE_INDEX_CD': 0.15,
        'POSITION_CD': 1e9,
        'SUMMON_CD': 3,
        'SIZE': (128, 128),
        'SPEED': (0, 0),
        'CAN_LOOT': False,
        'PRICE': 20,
    }
}